development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: vlog_dev

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: vlog_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: vlog_production
